# language file [Simplified Chinese:zh_CN; traditional Chinese:zh_TW; English:en_US]
# Restart the server when changing the language first time
language: en_US

# default title 
default: "§f[ §7player §f]"

# Please modify the default prefix and suffix before adding a title

# default title prefix
prefixBrackets: "§f[ "

# default title suffix
suffixBrackets: " §f]"

# display the title in chat
isChat: true

# display title format in chat
isChatFormat: " "

# The tab list and the title of the player's head are displayed, the default is off
# there are conflict with scoreboard plugin. please use papi for compatible
isTab: false

# the cooldown for toggle the title, The unit is second. the funtion will close if the cooldown is 0.
togglesCoolDown: 3

# using true or false to enable title buff function. The buff will load which using true. The buff will invalid when using false (can use in some RPG server or lobby server)
isEnableBuff: true

# using true or false to enable all buff. all player title will load when using true. all player can only load the title buff that they wearing
isAllBuff: false

# enable the automatic using the new tags when player get a new title
isAutoUse: false 

# enable for the update reminder. recommand be true.
isCheckUpdate: true

# Sending update reminders to the op when they login
isCheckUpdateToOpMsg: true

# enable cloud localization(Using cloud service resources to automatically localize various item names)
cloudChinesization: true

# title length limit for custom title 
customLength: 16

# Full version verification signature
sign: 123456